// topics.js
module.exports = [
  "Futur I",
  "Futur II",
  "Präsens",
  "Perfekt",
  "Präteritum",
  "Plusquamperfekt",
  "Passiv",
  "Konjunktiv I",
  "Konjunktiv II",
  "Genitiv",
  "Dativ",
  "Akkusativ",
  "Nominativ",
  "Modalverben",
  "Trennbare Verben",
  "Untrennbare Verben",
  "Reflexive Verben",
  "Adjektivdeklination",
  "Relativsätze",
  "Temporalsätze",
  "Kausalsätze",
  "Konditionalsätze",
  "Konsekutivsätze",
  "Finalsätze",
  "Präpositionen mit Dativ",
  "Präpositionen mit Akkusativ",
  "Präpositionen mit Wechsel",
  "Negation mit nicht/kein",
  "Wortstellung im Satz",
  "Fragesätze",
  "Imperativ",
  "Infinitivsätze mit zu",
  "Partizip I und II",
  "Nominalisierung",
  "Komparation der Adjektive",
  "Zeitangaben",
  "Ortsangaben",
  "Konnektoren",
  "Direkte Rede",
  "Indirekte Rede",
  "Rektion der Verben",
  "Wortbildung",
  "Trennbare Präfixe",
  "Untrennbare Präfixe",
  "Personalpronomen",
  "Possessivpronomen",
  "Demonstrativpronomen",
  "Relativpronomen",
  "Reflexivpronomen",
  "Fragepronomen",
  "Adverbien"
];
